import { SessionProvider } from "../components/SessionProvider";
import SideBar from "../components/SideBar";
import "../styles/globals.css";
import { getServerSession } from "next-auth";
import { authOptions } from "../pages/api/auth/[...nextauth]";
import Login from "../components/Login";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <head />
      <body>
        {!session ? (
          <Login />
        ) : (
          <SessionProvider session={session}>
            <div className="flex">
              {/* sidebar */}
              <div className=" bg-[#202123] max-w-xs h-screen overflow-y-auto md:min-w-[20rem]">
                <SideBar />
              </div>
              {/* client provider - notification */}
              <div className="flex-1 bg-[#343541]">{children}</div>
            </div>
          </SessionProvider>
        )}
      </body>
    </html>
  );
}
